<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net472</TargetFramework><AssemblyName>MonkStyle</AssemblyName><Version>0.1.0</Version><Nullable>disable</Nullable><GameManaged Condition="'$(GameManaged)' == ''">/home/bunta/.local/share/Steam/steamapps/common/Valheim/valheim_Data/Managed</GameManaged></PropertyGroup>
<ItemGroup><ProjectReference Include="../MonkStyle.Core/MonkStyle.Core.csproj"/>
<Reference Include="$(GameManaged)/assembly_*.dll"><Private>false</Private></Reference>
<Reference Include="$(GameManaged)/UnityEngine*.dll"><Private>false</Private></Reference>
<Reference Include="$(GameManaged)/Unity.TextMeshPro.dll"><Private>false</Private></Reference>
<Reference Include="../../../.deps/0Harmony.dll"><Private>false</Private></Reference>
<Reference Include="../../../.deps/BepInEx.dll"><Private>false</Private></Reference>
<Reference Include="../../../.deps/Jotunn.dll"><Private>false</Private></Reference>
</ItemGroup></Project>
