<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType><AssemblyName>ScrubclubPatcher</AssemblyName><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><ProjectReference Include="../Core/Core.csproj"/><EmbeddedResource Include="release-public.pem" LogicalName="ScrubclubPatcher.release-public.pem"/></ItemGroup></Project>
