<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net472</TargetFramework><AssemblyName>BlueDepot</AssemblyName><Version>0.1.4</Version><Nullable>disable</Nullable><GameManaged Condition="'$(GameManaged)' == ''">/home/bunta/.local/share/Steam/steamapps/common/Valheim/valheim_Data/Managed</GameManaged></PropertyGroup>
<ItemGroup><ProjectReference Include="../BlueDepot.Core/BlueDepot.Core.csproj"/>
<Reference Include="$(GameManaged)/assembly_*.dll"><Private>false</Private></Reference>
<Reference Include="$(GameManaged)/UnityEngine*.dll"><Private>false</Private></Reference>
<Reference Include="$(GameManaged)/Unity.TextMeshPro.dll"><Private>false</Private></Reference>
<Reference Include="../../.deps/*.dll"><Private>false</Private></Reference>
</ItemGroup></Project>
